name: Coordinates
main: com.github.syu6noob.coordinates.Coordinates
version: '${version}'
description: Displays your coordinates and the current world time in the action bar or sidebar.
author: syu6noob
website: https://github.com/syu6noob/coordinates
api-version: '1.21'
commands:
  coords:
    description: "Show or hide your coordinates and world time."
    usage: "/coords show <actionbar|scoreboard> | /coords hide"
    permission: coordinates.use
permissions:
  coordinates.use:
    description: "Use the coords command."
    default: true
